server:
  port: 0

spring:
  application:
    name: payroll-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payrolldb
    username: postgres
    password: Sachin_08_E_17
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: "*"
